# Generates a C++ header embedding every file in ${IN_DIR} as a
# polycalc::web::EmbeddedAsset entry, keyed by URL path ("/" for index.html,
# "/<name>" for everything else). Run at build time (not configure time) via
# add_custom_command in src/CMakeLists.txt, so editing a file under
# assets/web/ and rebuilding regenerates this automatically - no separate
# "make sure to copy the web/ folder next to the .exe" step, and no
# dependency on any bundler/build tool to produce it.
#
# Usage: cmake -DIN_DIR=<dir> -DOUT_FILE=<path> -P EmbedWebAssets.cmake

if(NOT DEFINED IN_DIR OR NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "EmbedWebAssets.cmake requires -DIN_DIR=... -DOUT_FILE=...")
endif()

file(GLOB ASSET_FILES RELATIVE "${IN_DIR}" "${IN_DIR}/*")
list(SORT ASSET_FILES)

set(HEADER_CONTENT "// Generated by cmake/EmbedWebAssets.cmake from assets/web/ - do not edit by hand.\n")
string(APPEND HEADER_CONTENT "#pragma once\n\n#include \"polycalc/web/HttpServer.hpp\"\n\nnamespace polycalc::web {\n\n")

set(ENTRIES "")
set(ASSET_INDEX 0)

foreach(FILE_NAME ${ASSET_FILES})
    set(FULL_PATH "${IN_DIR}/${FILE_NAME}")
    if(IS_DIRECTORY "${FULL_PATH}")
        continue()
    endif()

    if(FILE_NAME STREQUAL "index.html")
        set(URL_PATH "/")
    else()
        set(URL_PATH "/${FILE_NAME}")
    endif()

    get_filename_component(EXTENSION "${FILE_NAME}" EXT)
    string(TOLOWER "${EXTENSION}" EXTENSION)
    if(EXTENSION STREQUAL ".html")
        set(MIME "text/html; charset=utf-8")
    elseif(EXTENSION STREQUAL ".css")
        set(MIME "text/css; charset=utf-8")
    elseif(EXTENSION STREQUAL ".js")
        set(MIME "application/javascript; charset=utf-8")
    elseif(EXTENSION STREQUAL ".svg")
        set(MIME "image/svg+xml")
    elseif(EXTENSION STREQUAL ".json")
        set(MIME "application/json; charset=utf-8")
    else()
        set(MIME "application/octet-stream")
    endif()

    file(READ "${FULL_PATH}" FILE_CONTENT)

    # MSVC caps a single string literal (raw ones included) well under the
    # size of app.js, erroring "string too big, trailing characters
    # truncated". Adjacent string literals are concatenated by the compiler
    # before that limit applies to any individual token, so each file is
    # split into fixed-size chunks, each its own R"<delim>(...)<delim>"
    # literal, with nothing but whitespace between them - the reassembled
    # value is byte-for-byte identical to the source file either way, since
    # splitting a byte stream and concatenating the pieces back together
    # can't corrupt a multi-byte UTF-8 sequence that happened to straddle a
    # chunk boundary.
    string(LENGTH "${FILE_CONTENT}" CONTENT_LENGTH)
    set(CHUNK_SIZE 8000)
    set(CHUNK_OFFSET 0)
    set(CHUNK_INDEX 0)
    set(LITERAL_PARTS "")
    while(CHUNK_OFFSET LESS CONTENT_LENGTH)
        math(EXPR CHUNK_REMAINING "${CONTENT_LENGTH} - ${CHUNK_OFFSET}")
        if(CHUNK_REMAINING GREATER CHUNK_SIZE)
            set(THIS_CHUNK_SIZE ${CHUNK_SIZE})
        else()
            set(THIS_CHUNK_SIZE ${CHUNK_REMAINING})
        endif()
        string(SUBSTRING "${FILE_CONTENT}" ${CHUNK_OFFSET} ${THIS_CHUNK_SIZE} CHUNK)

        # A short delimiter: C++ raw-string d-char-sequences are capped at
        # 16 characters, and the delimiter must not appear as
        # ")<delim>\"" inside the chunk's own content.
        set(CHUNK_DELIM "PCWA${ASSET_INDEX}_${CHUNK_INDEX}")
        string(APPEND LITERAL_PARTS "R\"${CHUNK_DELIM}(${CHUNK})${CHUNK_DELIM}\" ")

        math(EXPR CHUNK_OFFSET "${CHUNK_OFFSET} + ${THIS_CHUNK_SIZE}")
        math(EXPR CHUNK_INDEX "${CHUNK_INDEX} + 1")
    endwhile()
    if(CONTENT_LENGTH EQUAL 0)
        set(LITERAL_PARTS "\"\"")
    endif()

    string(APPEND ENTRIES "    { \"${URL_PATH}\", \"${MIME}\", ${LITERAL_PARTS} },\n")

    math(EXPR ASSET_INDEX "${ASSET_INDEX} + 1")
endforeach()

if(ASSET_INDEX EQUAL 0)
    message(FATAL_ERROR "No web assets found under ${IN_DIR}")
endif()

string(APPEND HEADER_CONTENT "inline constexpr EmbeddedAsset kEmbeddedAssets[] = {\n${ENTRIES}};\n")
string(APPEND HEADER_CONTENT "inline constexpr std::size_t kEmbeddedAssetCount = sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]);\n\n")
string(APPEND HEADER_CONTENT "} // namespace polycalc::web\n")

file(WRITE "${OUT_FILE}" "${HEADER_CONTENT}")
